export type Data = {
    heading : string , 
    content : string[]
};

export const PageData : Data[] = [{
    heading: "What is emotional intelligence (EQ)?",
    content: ["Emotional intelligence (also known as emotional quotient or EQ) is the ability to understand, use, and manage your own emotions in positive ways to relieve stress, communicate effectively, empathize with others, overcome challenges and defuse conflict." , "Emotional intelligence helps you build stronger relationships, succeed at school and work, and achieve your career and personal goals. It can also help you to connect with your feelings, turn intention into action, and make informed decisions about what matters most to you."]
}, {
    heading: "The 4 Key Skills to Emotional intelligence:",
    content: ["Self-management: You’re able to control impulsive feelings and behaviors, manage your emotions in healthy ways, take initiative, follow through on commitments, and adapt to changing circumstances.", "Self-awareness: You recognize your own emotions and how they affect your thoughts and behavior. You know your strengths and weaknesses, and have self-confidence." , "Social awareness: You have empathy. You can understand the emotions, needs, and concerns of other people, pick up on emotional cues, feel comfortable socially, and recognize the power dynamics in a group or organization." , "Relationship management: You know how to develop and maintain good relationships, communicate clearly, inspire and influence others, work well in a team, and manage conflict."] 
} , {
    heading: "The importance of emotional intelligence (EQ)",
    content: ["As we know, it’s not the smartest people who are the most successful or the most fulfilled in life. You probably know people who are academically brilliant and yet are socially inept and unsuccessful at work or in their personal relationships. Intellectual ability or your intelligence quotient (IQ) isn’t enough on its own to achieve success in life. Yes, your IQ can help you get into college, but it’s your EQ that will help you manage the stress and emotions when facing your final exams. IQ and EQ exist in tandem and are most effective when they build off one another."]
}, {
    heading: "Emotional intelligence affects",
    content: ["Your performance at school or work. High emotional intelligence can help you navigate the social complexities of the workplace, lead and motivate others, and excel in your career. In fact, when it comes to gauging important job candidates, many companies now rate emotional intelligence as important as technical ability and employ EQ testing before hiring." , "Your physical health. If you’re unable to manage your emotions, you are probably not managing your stress either. This can lead to serious health problems. Uncontrolled stress raises blood pressure, suppresses the immune system, increases the risk of heart attacks and strokes, contributes to infertility, and speeds up the aging process. The first step to improving emotional intelligence is to learn how to manage stress."], 
},{
    heading: "Emotional intelligence affects",
    content: ["Your mental health. Uncontrolled emotions and stress can also impact your mental health, making you vulnerable to anxiety and depression. If you are unable to understand, get comfortable with, or manage your emotions, you’ll also struggle to form strong relationships. This in turn can leave you feeling lonely and isolated and further exacerbate any mental health problems." , "Your relationships. By understanding your emotions and how to control them, you’re better able to express how you feel and understand how others are feeling. This allows you to communicate more effectively and forge stronger relationships, both at work and in your personal life." , "Your social intelligence. Being in tune with your emotions serves a social purpose, connecting you to other people and the world around you. Social intelligence enables you to recognize friend from foe, measure another person’s interest in you, reduce stress, balance your nervous system through social communication, and feel loved and happy."], 
}, {
    heading: "Building emotional intelligence: Four key skills to increasing EQ",
    content: ["The skills that make up emotional intelligence can be learned at any time. However, it’s important to remember that there is a difference between simply learning about EQ and applying that knowledge to your life. Just because you know you should do something doesn’t mean you will—especially when you become overwhelmed by stress, which can override your best intentions.", "In order to permanently change behavior in ways that stand up under pressure, you need to learn how to overcome stress in the moment, and in your relationships, in order to remain emotionally aware."] 
} , {
    heading: "Skill 1: Self-management to build EQ",
    content: ["In order for you to engage your EQ, you must be able to use your emotions to make constructive decisions about your behavior. When you become overly stressed, you can lose control of your emotions and the ability to act thoughtfully and appropriately." , "Think about a time when stress has overwhelmed you. Was it easy to think clearly or make a rational decision? Probably not. When you become overly stressed, your ability to both think clearly and accurately assess emotions—your own and other people’s—becomes compromised." , "Emotions are important pieces of information that tell you about yourself and others, but in the face of stress that takes us out of our comfort zone, we can become overwhelmed and lose control of ourselves. With the ability to manage stress and stay emotionally present, you can learn to receive upsetting information without letting it override your thoughts and self-control. You’ll be able to make choices that allow you to control impulsive feelings and behaviors, manage your emotions in healthy ways, take initiative, follow through on commitments, and adapt to changing circumstances."]
} , {
    heading: "Skill 2: Self-awareness for EQ",
    content: [""]
}] 